# wrangler.toml (wrangler v3.88.0^)

name = "s4j-redirector"
main = "worker.js"
compatibility_date = "2025-10-10"

workers_dev = false

send_metrics = false

[[routes]]
pattern = "www.searchforjohn.com/*"
zone_name = "searchforjohn.com"

[observability]
enabled = false

[placement]
mode = "smart"
